// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Hamburger: typeof import('./components/Hamburger/index.vue')['default']
    Wj: typeof import('./components/wj/index.vue')['default']
  }
}

export {}
