#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

# Format and submit code according to lintstagedrc.js configuration
# 根据 lintstagedrc.js 配置格式化并提交代码。
npm run lint:lint-staged
